name: opencc
description: A dart library for conversion between Traditional and Simplified Chinese with natvie-assets.
version: 1.0.0
repository: https://github.com/lindeer/opencc

environment:
  sdk: ^3.3.0

dependencies:
  ffi: ^2.1.2
  native_assets_cli: ^0.6.0

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.24.0
